name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
        - main

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Run init
              run: terraform init

            - name: create plan 
              run: terraform plan